### ISSUE TITLE
I've done the required work before

### ISSUE THREAD

**Issue by Wh1teCl0ud** [Wh1teCl0ud/Portfolio_setup#6]
If you go to my [repo](https://github.com/Wh1teCl0ud/Portfolio_setup), in readme there is a "live demo link", by which I lead to an already deployed page with my project.
I did it right after completing the desktop version.

**Comment by mckent05** [comment]
Hi @Wh1teCl0ud , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Your project is working fine 👏 
- You have deployed your site properly 👍 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
